#!/usr/bin/with-contenv bash
set -e

# If a custom WebDAV config is provided, copy it to /config.yml
if [ -f /data/webdav.yaml ]; then
  cp /data/webdav.yaml /config.yml
fi

# Ensure that the WebDAV storage directory exists in /share
mkdir -p /share/webdav

# Start the WebDAV server.
# The "--config" flag tells it where to find its configuration,
# and "--data" tells it where to store files.
exec webdav --config /config.yml --data /share/webdav
